"""empty message

Revision ID: 3981efd3f0e9
Revises: dea03e6f86bc
Create Date: 2021-05-08 19:56:20.459617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3981efd3f0e9'
down_revision = 'dea03e6f86bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flavour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cheese_id', sa.Integer(), nullable=False),
    sa.Column('flavour', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['cheese_id'], ['cheese.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flavour')
    # ### end Alembic commands ###
