"""empty message

Revision ID: 6da11a7f2ce4
Revises: 12d7a88b0adb
Create Date: 2020-11-10 22:06:20.461783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6da11a7f2ce4'
down_revision = '12d7a88b0adb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cheese', sa.Column('name', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cheese', 'name')
    # ### end Alembic commands ###
