"""empty message

Revision ID: a56287ed831a
Revises: 6da11a7f2ce4
Create Date: 2021-05-07 19:50:25.991545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a56287ed831a'
down_revision = '6da11a7f2ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milk', sa.Column('pasteurized', sa.String(length=80), nullable=False))
    op.alter_column('type', 'type',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('type', 'type',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.drop_column('milk', 'pasteurized')
    # ### end Alembic commands ###
