"""empty message

Revision ID: bbf7443ef38c
Revises: 
Create Date: 2020-11-10 14:47:49.468490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbf7443ef38c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cheese',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rind', sa.String(length=80), nullable=False),
    sa.Column('colour', sa.String(length=80), nullable=False),
    sa.Column('vegetarian', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aroma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cheese_id', sa.Integer(), nullable=False),
    sa.Column('aroma', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['cheese_id'], ['cheese.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('country',
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cheese_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cheese_id'], ['cheese.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('milk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cheese_id', sa.Integer(), nullable=False),
    sa.Column('milk', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['cheese_id'], ['cheese.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('texture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cheese_id', sa.Integer(), nullable=False),
    sa.Column('texture', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['cheese_id'], ['cheese.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cheese_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['cheese_id'], ['cheese.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('type')
    op.drop_table('texture')
    op.drop_table('milk')
    op.drop_table('country')
    op.drop_table('aroma')
    op.drop_table('cheese')
    # ### end Alembic commands ###
